# Settings specifications for SILE's classes 
# firstContentFrame must always be named as "content", "first", "head" or "" for the sake of convenience
# It's not allowed to use the minus sign '-' for table title here, since they going to be reused in the lua code, so please use the lua naming convention here as well...   

[frames.cover.author]
left = ""
right = ""
top = ""
bottom = ""
[frames.cover.title]
left = "20%pw"
right = "80%pw"
# top = ""
height = "0"
bottom = "55%ph"
[frames.cover.institution]
left = ""
right = ""
top = ""
bottom = ""


[frames.right.content]
left = "2cm"
right = "100%pw-3cm"
top = "3cm"
bottom = "100%ph-2cm"
[frames.right.folio]
left = ""
right = ""
top = ""
bottom = ""
[frames.right.footnotes]
left = ""
right = ""
top = ""
bottom = ""
[frames.right.runningHead]
left = ""
right = ""
top = ""
bottom = ""


papersize = "a4"
folios      = true   
forprint    = true


[alingments]
toc             = "right"
folio           = "center"
chapter         = "left"
epigraph        = "right"
title           = "center"
author          = "center"
imprint         = "center"
editionNotice   = "center"
acknowledgement = "center"


[fonts]   # [family, size, weight, color]
toc       = ["Times New Roman", "12pt", 400]
isbn      = ["Times New Roman", "12pt", 300]
main      = ["Times New Roman", "12pt", 400]
title     = ["Times New Roman", "12pt", 800]
folio     = ["Times New Roman", "12pt", 500]
author    = ["Times New Roman", "12pt", 700]
headers   = ["Times New Roman", "12pt", 500]
imprint   = ["Times New Roman", "12pt", 800]
chapters  = ["Times New Roman", "12pt", 700]

[spacing]
words      = false
lines      = false
letters    = false
paragraphs = false

[headings]
topMargin = false
running   = false

[test]
show = true
