layout = ""
papersize = ""
folios = true
forprint = false
landscape = false
neverindent = false

[alingments]
toc             = ""
title           = ""
folio           = ""
author          = ""
chapter         = ""
imprint         = ""
epigraph        = ""
editionNotice   = ""
acknowledgement = ""


[fonts]   # [family, size, weight, variant, style, color]
#example  = ["arial", "13pt", 400, "smallcaps", "italic", "#ffffff"]
toc       = ["", "", 0, "", "", ""]
isbn      = ["", "", 0, "", "", ""]
main      = ["", "", 0, "", "", ""]
title     = ["", "", 0, "", "", ""]
folio     = ["", "", 0, "", "", ""]
author    = ["", "", 0, "", "", ""]
special   = ["", "", 0, "", "", ""] # for characters like ▩▤▧⌘
headers   = ["", "", 0, "", "", ""]
imprint   = ["", "", 0, "", "", ""]
chapters  = ["", "", 0, "", "", ""]
epigraph  = ["", "", 0, "", "", ""]
footnotes = ["", "", 0, "", "", ""]
serial    = ["", "", 0, "", "", ""]

[spacing]
words      = false
lines      = false
letters    = false
paragraphs = false

[headings]
topMargin = false
running   = false

[toc] # this is likely going to be used for list of illustrations and abbreviations as well...
double = false

[test]
show = false

[ellipsis]
symbol = "" #■□▣▥▤▦▨▧▩⌘⁂
rotate = false
size = ""
font = ""
weight = 0

[dingbats]
amount = 0

[dingbats.ratio]
width = ""
height = ""

[colors] # only in hexadecimal
main = "#"
secondary = "#"

[frames.master.frame]
left = ""
right = ""
top = ""
bottom = ""
#height = ""
#width = ""

